// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0agNLEiUwFiqDWYf07Ae-541PwYixVAE',
    appId: '1:295684564949:web:558b2b63fedf95929a3f5c',
    messagingSenderId: '295684564949',
    projectId: 'cooleappdominik',
    authDomain: 'cooleappdominik.firebaseapp.com',
    storageBucket: 'cooleappdominik.firebasestorage.app',
    measurementId: 'G-GVE96WMKQH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm2O9auRne90Ez2pwsdFw-5Yh1DJGz-jY',
    appId: '1:295684564949:android:0e902a45c4d724619a3f5c',
    messagingSenderId: '295684564949',
    projectId: 'cooleappdominik',
    storageBucket: 'cooleappdominik.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATEZLoy75W2LgLw7n8pA4hC-f5-dMjXBY',
    appId: '1:295684564949:ios:7802495b1d8fbcc89a3f5c',
    messagingSenderId: '295684564949',
    projectId: 'cooleappdominik',
    storageBucket: 'cooleappdominik.firebasestorage.app',
    iosBundleId: 'com.example.servusmona',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATEZLoy75W2LgLw7n8pA4hC-f5-dMjXBY',
    appId: '1:295684564949:ios:7802495b1d8fbcc89a3f5c',
    messagingSenderId: '295684564949',
    projectId: 'cooleappdominik',
    storageBucket: 'cooleappdominik.firebasestorage.app',
    iosBundleId: 'com.example.servusmona',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0agNLEiUwFiqDWYf07Ae-541PwYixVAE',
    appId: '1:295684564949:web:90cdf762a9bcc6fa9a3f5c',
    messagingSenderId: '295684564949',
    projectId: 'cooleappdominik',
    authDomain: 'cooleappdominik.firebaseapp.com',
    storageBucket: 'cooleappdominik.firebasestorage.app',
    measurementId: 'G-E3PRG2GYBM',
  );
}
